# Generated by Django 4.2.30 on 2026-06-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='United States', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, help_text='Name the member prefers to be called.', max_length=100, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('baptismal_date', models.DateField(blank=True, null=True)),
                ('membership_date', models.DateField(blank=True, null=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('previous_congregation_notes', models.TextField(blank=True, null=True)),
                ('moved_to_area_date', models.DateField(blank=True, null=True)),
                ('lives_with', models.CharField(blank=True, max_length=200, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated')], max_length=20, null=True)),
                ('was_previously_married', models.BooleanField(default=False)),
                ('has_children', models.BooleanField(default=False)),
                ('children_in_congregation', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_members', to='churchmembers.address')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorshipArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuestInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('Phone', 'Phone'), ('Email', 'Email'), ('Text', 'Text'), ('WhatsApp', 'WhatsApp'), ('No Preference', 'No Preference')], max_length=20, null=True)),
                ('consent_to_contact', models.BooleanField(default=False)),
                ('visit_type', models.CharField(blank=True, choices=[('First Time', 'First Time'), ('Returning', 'Returning'), ('Other', 'Other')], max_length=20, null=True)),
                ('invitation_source', models.CharField(blank=True, choices=[('Invited by Member', 'Invited by Member'), ('Came Voluntarily', 'Came Voluntarily'), ('Church Outreach', 'Church Outreach'), ('Online/Social Media', 'Online/Social Media'), ('Other', 'Other')], max_length=30, null=True)),
                ('invitation_notes', models.TextField(blank=True, null=True)),
                ('new_to_area', models.BooleanField(default=False)),
                ('would_like_visit', models.BooleanField(default=False)),
                ('would_like_more_info', models.BooleanField(default=False)),
                ('interested_in_membership', models.BooleanField(default=False)),
                ('interested_in_bible_study', models.BooleanField(default=False)),
                ('interested_in_children_ministry', models.BooleanField(default=False)),
                ('interested_in_youth_ministry', models.BooleanField(default=False)),
                ('life_stage', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Single Parent', 'Single Parent'), ('Widowed', 'Widowed'), ('College Student', 'College Student'), ('High School Student', 'High School Student'), ('Middle School Student', 'Middle School Student')], max_length=30, null=True)),
                ('age_group', models.CharField(blank=True, choices=[('Under 20', 'Under 20'), ('20s', '20s'), ('30s', '30s'), ('40s', '40s'), ('50s', '50s'), ('60s', '60s'), ('70s+', '70s+')], max_length=20, null=True)),
                ('has_children_at_home', models.BooleanField(default=False)),
                ('number_of_children', models.PositiveIntegerField(blank=True, null=True)),
                ('home_church', models.CharField(blank=True, max_length=200, null=True)),
                ('prayer_request', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='churchmembers.address')),
                ('assigned_follow_up_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_guest_followups', to='churchmembers.churchmember')),
                ('invited_by_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_guests', to='churchmembers.churchmember')),
            ],
            options={
                'ordering': ['-visit_date', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Congregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pastor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='congregations', to='churchmembers.address')),
            ],
        ),
        migrations.AddField(
            model_name='churchmember',
            name='ministries',
            field=models.ManyToManyField(blank=True, related_name='members', to='churchmembers.ministry'),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='originating_congregation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_members', to='churchmembers.congregation'),
        ),
        migrations.AddField(
            model_name='churchmember',
            name='worship_areas',
            field=models.ManyToManyField(blank=True, related_name='members', to='churchmembers.worshiparea'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Absent', 'Absent'), ('In Person', 'In Person'), ('Zoom', 'Zoom'), ('Excused', 'Excused'), ('Late', 'Late')], default='Absent', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='churchmembers.churchmember')),
            ],
            options={
                'ordering': ['-date', 'member'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('member', 'date'), name='unique_member_attendance_per_date'),
        ),
    ]
