# Generated by Django 4.2.30 on 2026-06-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchmembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestinformation',
            options={'ordering': ['-visit_date', 'surname', 'first_name']},
        ),
        migrations.AddField(
            model_name='guestinformation',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guestinformation',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guestinformation',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guestinformation',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guestinformation',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
