# Generated by Django 4.2.30 on 2026-06-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchmembers', '0003_mediacategory_speaker_mediaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_photos/'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ministry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ministries/'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
